
from __future__ import annotations

from typing import Dict, Any, List
from datetime import datetime


def now_iso() -> str:
    """Return current UTC time in ISO format."""
    return datetime.utcnow().isoformat(timespec="seconds") + "Z"


def code_block(text: str, lang: str = "text") -> str:
    """Wrap text in a Markdown code block."""
    text = text or ""
    return f"```{lang}\n{text}\n```"


def extract_variants(results: Dict[str, Any]) -> List[Dict[str, Any]]:
    """
    Convert results.json (keyed by mutation index)
    into a list of per-variant dictionaries.
    """
    variants = []
    for index, data in results.items():
        if not isinstance(data, dict):
            continue

        variant = {
            "index": int(index),
            "diagnostician": data.get("diagnostician", {}),
            "engineer": data.get("engineer", {}),
            "regulator": data.get("regulator", {}),
        }
        variants.append(variant)

    return variants


def therapy_feasibility(engineer: Dict[str, Any]) -> str:
    """
    Decide whether a CRISPR therapy is constructible.
    """
    repair = engineer.get("repair_template", {})
    too_short = repair.get("too_short_context", False)
    templates = repair.get("templates", [])

    if too_short or not templates:
        return "NOT CONSTRUCTIBLE"

    return "CONSTRUCTIBLE"


def safety_summary(regulator: Dict[str, Any]) -> str:
    """
    Return short safety summary from regulator output.
    """
    ranked = regulator.get("ranked_candidates", [])
    if not ranked:
        return "UNKNOWN"

    top = ranked[0]
    return f"{top.get('recommendation', 'UNKNOWN')} (risk: {top.get('risk_level', 'UNKNOWN')})"


def build_markdown_report(results: Dict[str, Any]) -> str:
    """
    Build a human-readable clinical report in Markdown
    from the aggregated results.json.
    """
    run_id = now_iso()
    variants = extract_variants(results)

    lines: List[str] = []


    lines.append("# 🧬 CRISPR-OS — Clinical Report")
    lines.append(f"**Run ID:** `{run_id}`")
    lines.append("")


    lines.append("## Executive Summary")

    pathogenic = 0
    constructible = 0

    for v in variants:
        if v["diagnostician"].get("risk_level") == "Pathogenic":
            pathogenic += 1
        if therapy_feasibility(v["engineer"]) == "CONSTRUCTIBLE":
            constructible += 1

    lines.append(
        f"- **{len(variants)} genetic variants** were analyzed.\n"
        f"- **{pathogenic} variants** are classified as pathogenic.\n"
        f"- **{constructible} variants** have a technically constructible CRISPR therapy.\n"
    )

  
    lines.append("## Variant Details")

    for v in variants:
        idx = v["index"]
        diag = v["diagnostician"]
        eng = v["engineer"]
        reg = v["regulator"]

        lines.append(f"### Variant at position {idx}")

      
        lines.append("**What was found**")
        lines.append(
            f"- Gene: `{diag.get('target_gene', 'N/A')}`\n"
            f"- Change: `{diag.get('ref', '?')} → {diag.get('alt', '?')}`\n"
            f"- Risk level: **{diag.get('risk_level', 'UNKNOWN')}**\n"
            f"- Interpretation: {diag.get('reasoning', '')}\n"
        )

        feasibility = therapy_feasibility(eng)
        lines.append("**CRISPR therapy feasibility**")
        lines.append(f"- Status: **{feasibility}**")

        if feasibility == "CONSTRUCTIBLE":
            cand = eng.get("candidates", [{}])[0]
            lines.append("- Proposed gRNA:")
            lines.append(code_block(cand.get("spacer_sequence", "")))

   
        lines.append("**Safety assessment**")
        lines.append(f"- {safety_summary(reg)}")

   
        lines.append("**Recommended next step**")

        if feasibility != "CONSTRUCTIBLE":
            lines.append(
                "- Provide a longer DNA context or alternative PAM sites to enable HDR repair."
            )
        elif safety_summary(reg).startswith("WARNING"):
            lines.append(
                "- Re-design gRNA to reduce off-target risk before clinical use."
            )
        else:
            lines.append(
                "- Therapy design is ready for further validation and export."
            )

        lines.append("")


    lines.append("## Notes")
    lines.append(
        "- This report is generated by an experimental AI system.\n"
        "- It is intended for educational and demonstration purposes only."
    )

    return "\n".join(lines)
